# Generated by Django 4.2.5 on 2023-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=8)),
                ('vehicle_type', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=150)),
                ('charge', models.IntegerField()),
            ],
        ),
    ]
