# Generated by Django 4.2.5 on 2023-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(max_length=10)),
                ('chassis_num', models.CharField(max_length=17)),
                ('engine_num', models.CharField(max_length=19)),
                ('vehicle_class', models.CharField(max_length=9)),
                ('vehicle_type', models.CharField(max_length=4)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
