# Generated by Django 4.2.5 on 2023-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rideBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_loc', models.CharField(max_length=150)),
                ('drop_loc', models.CharField(max_length=150)),
                ('vehicle_class', models.CharField(max_length=9)),
                ('vehicle_type', models.CharField(max_length=4)),
                ('booked_by', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('car', models.CharField(max_length=10)),
            ],
        ),
    ]
